### ISSUE TITLE
[Android] Final Fantasys (3 3D, 4 3D, 5, 6, 7, 8, 9), Honkai Star Rail, Stardew Valley

### ISSUE THREAD

**Issue by biomagnet** [Jetup13/Retroid-Pocket-5-Wiki#1]
Game Name|Playable|Controller Support|Fixes/Notes|
:--------|:------:|:-----------------:|:----------|
[Final Fantasy III (3D Remake)](https://play.google.com/store/apps/details?id=com.square_enix.android_googleplay.FFIII_GP)|🟩|🟩|
[Final Fantasy IV (3D Remake)](https://play.google.com/store/apps/details?id=com.square_enix.android_googleplay.FFIV_GP)|🟩|🟩|
[Final Fantasy IX](https://play.google.com/store/apps/details?id=com.square_enix.FFIXww.android_googleplay)|🟩|🟩|
[Final Fantasy V](https://play.google.com/store/apps/details?id=com.square_enix.android_googleplay.FFPR5)|🟩|🟩|
[Final Fantasy VI](https://play.google.com/store/apps/details?id=com.square_enix.android_googleplay.FFPR6)|🟩|🟩|
[Final Fantasy VII](https://play.google.com/store/apps/details?id=com.square_enix.android_googleplay.FFVII)|🟩|🟩| 
[Final Fantasy VIII Remastered](https://play.google.com/store/apps/details?id=com.square_enix.android_googleplay.FFVIII)|🟩|🟩|
[Honkai: Star Rail](https://play.google.com/store/apps/details?id=com.HoYoverse.hkrpgoversea)|🟩|🟩|`Phone Menu > Settings > Others > Switch Control Mode > Controller Mode`. Cannot be changed until you have loaded in.</br> Set `L2/R2 Mode: Analog` to use Ults with LT.|
[Stardew Valley](https://play.google.com/store/apps/details?id=com.chucklefish.stardewvalley)|🟩|🟧|Some controller bugs introduced with 1.6 update.|

```
Game Name|Playable|Controller Support|Fixes/Notes|
:--------|:------:|:-----------------:|:----------|
[Final Fantasy III (3D Remake)](https://play.google.com/store/apps/details?id=com.square_enix.android_googleplay.FFIII_GP)|🟩|🟩|
[Final Fantasy IV (3D Remake)](https://play.google.com/store/apps/details?id=com.square_enix.android_googleplay.FFIV_GP)|🟩|🟩|
[Final Fantasy IX](https://play.google.com/store/apps/details?id=com.square_enix.FFIXww.android_googleplay)|🟩|🟩|
[Final Fantasy V](https://play.google.com/store/apps/details?id=com.square_enix.android_googleplay.FFPR5)|🟩|🟩|
[Final Fantasy VI](https://play.google.com/store/apps/details?id=com.square_enix.android_googleplay.FFPR6)|🟩|🟩|
[Final Fantasy VII](https://play.google.com/store/apps/details?id=com.square_enix.android_googleplay.FFVII)|🟩|🟩| 
[Final Fantasy VIII Remastered](https://play.google.com/store/apps/details?id=com.square_enix.android_googleplay.FFVIII)|🟩|🟩|
[Honkai: Star Rail](https://play.google.com/store/apps/details?id=com.HoYoverse.hkrpgoversea)|🟩|🟩|`Phone Menu > Settings > Others > Switch Control Mode > Controller Mode`. Cannot be changed until you have loaded in.</br> Set `L2/R2 Mode: Analog` to use Ults with LT.|
[Stardew Valley](https://play.google.com/store/apps/details?id=com.chucklefish.stardewvalley)|🟩|🟧|Some controller bugs introduced with 1.6 update.|
```

**Comment by Jetup13** [comment]
Perfect! I added them all and added credit to you. 
Don't hesitate if there's anything wrong or something I need to remove

Thanks!

**Comment by biomagnet** [comment]
Oh, no worries! I didn't even need a line of credit, haha. Just happy to contribute! I hope more people end up using this resource, it's very useful.

**Comment by Jetup13** [comment]
Thanks, I updated the entry
