### ISSUE TITLE
[Android] Torchlight: Infinite

### ISSUE THREAD

**Issue by CYPH3RsD0M41N** [Jetup13/Retroid-Pocket-5-Wiki#10]
Game Name|Playable|Controller Support|Fixes/Notes|
:--------|:------:|:-----------------:|:----------|
[Torchlight: Infinite](https://play.google.com/store/apps/details?id=com.xd.TLglobal&hl=en)|🟦|🟧|

**Comment by Jetup13** [comment]
Added to the list, thanks!
