### ISSUE TITLE
[Android] Wreckfest

### ISSUE THREAD

**Issue by CYPH3RsD0M41N** [Jetup13/Retroid-Pocket-5-Wiki#11]
Game Name|Playable|Controller Support|Fixes/Notes|
:--------|:------:|:-----------------:|:----------|
[Wreckfest](https://play.google.com/store/search?q=wreckfest&c=apps&hl=en)|🟩|🟩|

**Comment by Jetup13** [comment]
Wreckfest is already on the list but thanks for checking too!
