### ISSUE TITLE
[Android] Grand Theft Auto III - Definitive Edition 

### ISSUE THREAD

**Issue by CYPH3RsD0M41N** [Jetup13/Retroid-Pocket-5-Wiki#12]
Game Name|Playable|Controller Support|Fixes/Notes|
:--------|:------:|:-----------------:|:----------|
[Grand Theft Auto III - Definitive Edition](https://play.google.com/store/apps/details?id=com.rockstargames.gta3.de)|🟦|🟩|

**Comment by Jetup13** [comment]
Added to the list, thanks!
