### ISSUE TITLE
[Android] Grand Theft Auto: San Andreas - Definitive Edition

### ISSUE THREAD

**Issue by CYPH3RsD0M41N** [Jetup13/Retroid-Pocket-5-Wiki#14]
Game Name|Playable|Controller Support|Fixes/Notes|
:--------|:------:|:-----------------:|:----------|
[Grand Theft Auto: San Andreas - Definitive Edition](https://play.google.com/store/apps/details?id=com.rockstargames.gtasa.de)|🟦|🟩|

**Comment by Jetup13** [comment]
Added to the list, thanks!
