### ISSUE TITLE
[Android] Nimian Legends: Vandgels

### ISSUE THREAD

**Issue by CYPH3RsD0M41N** [Jetup13/Retroid-Pocket-5-Wiki#15]
Game Name|Playable|Controller Support|Fixes/Notes|
:--------|:------:|:-----------------:|:----------|
[Nimian Legends: Vandgels](https://play.google.com/store/apps/details?id=com.protopop.vandgels)|🟦|🟩|

**Comment by Jetup13** [comment]
Added to the list, thanks!
