### ISSUE TITLE
[Android] Infinity NIkki

### ISSUE THREAD

**Issue by CYPH3RsD0M41N** [Jetup13/Retroid-Pocket-5-Wiki#19]
Game Name|Playable|Controller Support|Fixes/Notes|
:--------|:------:|:-----------------:|:----------|
[Infinity NIkki](https://play.google.com/store/apps/details?id=com.infoldgames.infinitynikkien)|🟪|🟩| For Controller Support: `Settings > Controls > Controller`

**Comment by Jetup13** [comment]
Thanks, what should I should I add for the playability 🟩|🟦🟧|🟥?  (I should maybe have a special spot for Aurora Store requirement 🤔)

**Comment by CYPH3RsD0M41N** [comment]
The game allows you to change the graphics settings to avoid any issues,
however, it's not *super* perfect. It is playable, though.

**Comment by Jetup13** [comment]
Thanks! I added it
