### ISSUE TITLE
[Android] Exiled Kingdoms Full

### ISSUE THREAD

**Issue by CYPH3RsD0M41N** [Jetup13/Retroid-Pocket-5-Wiki#20]
Game Name|Playable|Controller Support|Fixes/Notes|
:--------|:------:|:-----------------:|:----------|
[Exiled Kingdoms Full](https://play.google.com/store/apps/details?id=net.fdgames.ek.androidfull)|🟩|🟧|For Custom Mapping: `Settings > Controller Setup`. Certain buttons may not be mapped and custom mappings may reset to default values on exit.

**Comment by Jetup13** [comment]
Added, thanks!
