### ISSUE TITLE
[Android] Gangstar Vegas

### ISSUE THREAD

**Issue by CYPH3RsD0M41N** [Jetup13/Retroid-Pocket-5-Wiki#21]
Game Name|Playable|Controller Support|Fixes/Notes|
:--------|:------:|:-----------------:|:----------|
[Gangstar Vegas](https://play.google.com/store/apps/details?id=com.gameloft.android.ANMP.GloftGGHM)|🟩|🟧|For Custom Mapping: `Settings > Controls > Controller > Right Arrow`. Mapping buttons is quite a nuisance, and takes time for them to properly register. Also, most buttons cannot be mapped and mappings may reset on exit.

**Comment by Jetup13** [comment]
Added, thanks
