### ISSUE TITLE
[Android] Gangstar New Orleans

### ISSUE THREAD

**Issue by CYPH3RsD0M41N** [Jetup13/Retroid-Pocket-5-Wiki#22]
Game Name|Playable|Controller Support|Fixes/Notes|
:--------|:------:|:-----------------:|:----------|
[Gangstar New Orleans](https://play.google.com/store/apps/details?id=com.gameloft.android.ANMP.GloftOLHM)|🟦|🟥|

**Comment by Jetup13** [comment]
Added thanks!
