### ISSUE TITLE
[Android] Animal Crossing: Pocket Camp Complete

### ISSUE THREAD

**Issue by CYPH3RsD0M41N** [Jetup13/Retroid-Pocket-5-Wiki#23]
Game Name|Playable|Controller Support|Fixes/Notes|
:--------|:------:|:-----------------:|:----------|
[Animal Crossing: Pocket Camp Complete](https://play.google.com/store/apps/details?id=com.nintendo.zasa)|🟩|🟥|Vertical-only game.

**Comment by Jetup13** [comment]
Added thanks!
