### ISSUE TITLE
Permission to redirect a domain?

### ISSUE THREAD

**Issue by sottey** [Jetup13/Retroid-Pocket-5-Wiki#24]
Hey there! I am not sure how to reach out on Github so I am creating an issue. Hope that's ok.

I am a big fan of the PSPDevWiki, so I planned to create a similar thing for the Pocket 5. I purchased the domain Pocket5.org for that purpose. Now I see your amazing offering and thought it might be good to just have my domain redirect to your wiki. Would this be ok with you? If not, totally ok, just thought I would ask.

Thanks!

**Comment by Jetup13** [comment]
As long as it doesn't contain copyrighted or illegal material sure. 🤷‍♂️

**Comment by sottey** [comment]
Nice. Just a forward, not a site,. so anyone who goes to pocket5.org will end up on your wiki. Thanks!

**Comment by Jetup13** [comment]
Oh ok! That's ok then
