### ISSUE TITLE
[Android] Solo Leveling: Arise

### ISSUE THREAD

**Issue by CYPH3RsD0M41N** [Jetup13/Retroid-Pocket-5-Wiki#25]
Game Name|Playable|Controller Support|Fixes/Notes|
:--------|:------:|:-----------------:|:----------|
[Solo Leveling: Arise](https://play.google.com/store/apps/details?id=com.netmarble.sololv)|🟦|🟩| `For Controller Support: Settings > Controls > Gamepad`

**Comment by Jetup13** [comment]
Added thanks!
