### ISSUE TITLE
[Android] Crunchyroll: Blossom Tales II

### ISSUE THREAD

**Issue by CYPH3RsD0M41N** [Jetup13/Retroid-Pocket-5-Wiki#27]
Game Name|Playable|Controller Support|Fixes/Notes|
:--------|:------:|:-----------------:|:----------|
[Crunchyroll: Blossom Tales II](https://play.google.com/store/apps/details?id=com.crunchyroll.gv.blossomtales2.game)|🟩|🟩|Requires a Crunchyroll subscription in order to be played.

**Comment by Jetup13** [comment]
Added, thanks!
