### ISSUE TITLE
[Android] Legend of the Skyfish 2 / Retro City Rampage: DX / Zenonia 4 / Zenonia 5

### ISSUE THREAD

**Issue by CYPH3RsD0M41N** [Jetup13/Retroid-Pocket-5-Wiki#29]
Game Name|Playable|Controller Support|Fixes/Notes|
:--------|:------:|:-----------------:|:----------|
[Legend of the Skyfish 2](https://play.google.com/store/apps/details?id=br.com.mothergaia.skyfish2)|🟩|🟩|To fix the broken trigger controls: `Swipe down to access the Quick Settings & Change L2/R2 mode to "Analog."`
[Retro City Rampage DX](https://play.google.com/store/apps/details?id=com.vblank.RCRDX)|🟦|🟩|May randomly crash on initial startup, but fully playable.
[Zenonia 4](https://play.google.com/store/apps/details?id=com.gamevil.zenonia4.global)|🟩|🟥|Face buttons, when pressed, will make the screen flash orange for some reason. The only controls that work are the directional buttons.
[Zenonia 5](https://play.google.com/store/apps/details?id=com.gamevil.zenonia5.global)|🟩|🟥|

**Comment by Jetup13** [comment]
Added thanks! I never knew Retro City Rampage came out on Android

**Comment by CYPH3RsD0M41N** [comment]
It's been out for awhile. Also, Vblank recently released Shakedown Hawaii
for iOS. I really hope it comes out on Android as well.
