### ISSUE TITLE
[Frontend] Add Console Launcher

### ISSUE THREAD

**Issue by likeich** [Jetup13/Retroid-Pocket-5-Wiki#3]
I recommend adding Console Launcher to the list of Android frontends, like below. The Google Play version is older and the Github version is far more updated and has emulation frontend support.
(full disclosure: I am the developer)

`[Console Launcher](https://play.google.com/store/apps/details?id=com.k2.consolelauncher)|Free / In-App Purchases|[Frontend Support](https://github.com/likeich/console-launcher)`

![Screenshot_20241114-141050 (1)](https://github.com/user-attachments/assets/ff769bd6-125e-4a19-90dc-772dc5ea1573)
![Screenshot_20241114-150154 (1)](https://github.com/user-attachments/assets/78be4276-b3d1-4363-ae8c-c910a70cd6bd)
![Screenshot_20241114-141110 (1)](https://github.com/user-attachments/assets/87570ecd-0e6b-4f88-b594-2207715733a9)

**Comment by Jetup13** [comment]
Never heard of this launcher before, thanks for telling me! Added to the list, thanks
