### ISSUE TITLE
[Android] Star Wars: Knights of the Old Republic (I & II)

### ISSUE THREAD

**Issue by biomagnet** [Jetup13/Retroid-Pocket-5-Wiki#4]
Game Name|Playable|Controller Support|Fixes/Notes|
:--------|:------:|:-----------------:|:----------|
[Star Wars: KotOR](https://play.google.com/store/apps/details?id=com.aspyr.swkotor)|🟩|🟩|Compatible with [mods made for PC](https://kotor.neocities.org/modding/)
[Star Wars: KotOR II](https://play.google.com/store/apps/details?id=com.aspyr.swkotorii)|🟩|🟩|Compatible with [mods made for PC](https://kotor.neocities.org/modding/)

```Game Name|Playable|Controller Support|Fixes/Notes|
:--------|:------:|:-----------------:|:----------|
[Star Wars: KotOR](https://play.google.com/store/apps/details?id=com.aspyr.swkotor)|🟩|🟩|Compatible with [mods made for PC](https://kotor.neocities.org/modding/)
[Star Wars: KotOR II](https://play.google.com/store/apps/details?id=com.aspyr.swkotorii)|🟩|🟩|Compatible with [mods made for PC](https://kotor.neocities.org/modding/)```

**Comment by Jetup13** [comment]
Thanks, added to the list!
