### ISSUE TITLE
[Android] Evoland

### ISSUE THREAD

**Issue by CYPH3RsD0M41N** [Jetup13/Retroid-Pocket-5-Wiki#5]
Game Name|Playable|Controller Support|Fixes/Notes|
:--------|:------:|:-----------------:|:----------|
[Evoland](https://play.google.com/store/apps/details?id=air.com.shirogames.evoland12&hl=en)|🟩|🟩|

**Comment by Jetup13** [comment]
Added to the list, thanks!
