### ISSUE TITLE
[Android] Evoland 2

### ISSUE THREAD

**Issue by CYPH3RsD0M41N** [Jetup13/Retroid-Pocket-5-Wiki#6]
Game Name|Playable|Controller Support|Fixes/Notes|
:--------|:------:|:-----------------:|:----------|
[Evoland 2](https://play.google.com/store/apps/details?id=com.playdigious.evoland2&hl=en)|🟩|🟩|

**Comment by Jetup13** [comment]
Added to the list, thanks!
