### ISSUE TITLE
[Android] Titan Quest: Ultimate Edition

### ISSUE THREAD

**Issue by CYPH3RsD0M41N** [Jetup13/Retroid-Pocket-5-Wiki#7]
Game Name|Playable|Controller Support|Fixes/Notes|
:--------|:------:|:-----------------:|:----------|
[Titan Quest: Ultimate Edition](https://play.google.com/store/apps/details?id=com.hg.titanquestultimate&hl=en)|🟩|🟩|

**Comment by Jetup13** [comment]
Added to the list, thanks!
