### ISSUE TITLE
[Android] Diablo Immortal

### ISSUE THREAD

**Issue by CYPH3RsD0M41N** [Jetup13/Retroid-Pocket-5-Wiki#9]
Game Name|Playable|Controller Support|Fixes/Notes|
:--------|:------:|:-----------------:|:----------|
[Diablo Immortal](https://play.google.com/store/apps/details?id=com.blizzard.diablo.immortal&hl=en)|🟦|🟧|

**Comment by Jetup13** [comment]
Added to the list, thanks!
